version: '3.8'

services:
  postgres:
    image: postgres:13.16
    restart: always
    container_name: postgres
    shm_size: 512mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: webflux
      POSTGRES_DB: webflux_kafka
    volumes:
      - ./postrgres_init.sql:/docker-entrypoint-initdb.d/postrgres_init.sql:ro